In [1]:
import pandas as pd
import numpy as np
import ast  # to convert string to python dictionary

In [2]:
credit = pd.read_csv("dataset/credits.csv")

In [3]:
credit['cast'] = credit['cast'].apply(ast.literal_eval)
credit['crew'] = credit['crew'].apply(ast.literal_eval)

In [4]:
credit

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': 'Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862
...,...,...,...
45471,"[{'cast_id': 0, 'character': '', 'credit_id': ...","[{'credit_id': '5894a97d925141426c00818c', 'de...",439050
45472,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",111109
45473,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",67758
45474,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",227506
45475,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",461257

In [5]:
metadata = pd.read_csv("dataset/movies_metadata_processed.csv")

In [6]:
metadata

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45458,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1
45459,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3
45460,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6
45461,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0
45462,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0

In [7]:
columns_to_drop = [
    'belongs_to_collection',
    'budget',
    'homepage',
    'imdb_id',
    'poster_path',
    'production_countries',
    'revenue',
    'runtime',
    'spoken_languages',
    'status',
    'tagline',
    'video',
    'original_language',
    'release_date',
    'vote_average',
    'popularity',
    'adult',
    'vote_count',
]
metadata = metadata.drop(columns_to_drop, axis=1)

In [8]:
metadata['genres'] = metadata['genres'].apply(ast.literal_eval)
metadata['production_companies'] = metadata['production_companies'].apply(ast.literal_eval)
metadata = metadata[metadata['genres'].apply(len) > 0]

In [9]:
metadata.isnull().sum()

genres                    0
id                        0
original_title            0
overview                697
production_companies      0
title                     0
dtype: int64

In [10]:
metadata.dropna(inplace=True)

In [11]:
metadata.isnull().sum()

genres                  0
id                      0
original_title          0
overview                0
production_companies    0
title                   0
dtype: int64

In [12]:
credit

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': 'Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862
...,...,...,...
45471,"[{'cast_id': 0, 'character': '', 'credit_id': ...","[{'credit_id': '5894a97d925141426c00818c', 'de...",439050
45472,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",111109
45473,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",67758
45474,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",227506
45475,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",461257

In [13]:
hash_table = {}
for i, id in enumerate(credit["id"]):
    # print(credit.iloc[i].drop(['id']))
    hash_table[id] = credit.iloc[i].drop(['id'])

In [14]:
hash_table[862]

cast    [{'cast_id': 14, 'character': 'Woody (voice)',...
crew    [{'credit_id': '52fe4284c3a36847f8024f49', 'de...
Name: 0, dtype: object

In [15]:
metadata

,genres,id,original_title,overview,production_companies,title
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'name': 'Pixar Animation Studios', 'id': 3}]",Toy Story
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",Jumanji
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",Grumpier Old Men
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",[{'name': 'Twentieth Century Fox Film Corporat...,Waiting to Exhale
4,"[{'id': 35, 'name': 'Comedy'}]",11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'name': 'Sandollar Productions', 'id': 5842}...",Father of the Bride Part II
...,...,...,...,...,...,...
45456,"[{'id': 878, 'name': 'Science Fiction'}]",222848,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,"[{'name': 'Concorde-New Horizons', 'id': 4688}]",Caged Heat 3000
45457,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",30840,Robin Hood,"Yet another version of the classic epic, with ...","[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...",Robin Hood
45458,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",439050,رگ خواب,Rising and falling between a man and woman.,[],Subdue
45459,"[{'id': 18, 'name': 'Drama'}]",111109,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,"[{'name': 'Sine Olivia', 'id': 19653}]",Century of Birthing
45460,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",67758,Betrayal,"When one of her hits goes wrong, a professiona...","[{'name': 'American World Pictures', 'id': 6165}]",Betrayal

In [16]:
metadata['credits'] = metadata['id']

In [17]:
metadata

,genres,id,original_title,overview,production_companies,title,credits
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'name': 'Pixar Animation Studios', 'id': 3}]",Toy Story,862
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",Jumanji,8844
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",Grumpier Old Men,15602
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",[{'name': 'Twentieth Century Fox Film Corporat...,Waiting to Exhale,31357
4,"[{'id': 35, 'name': 'Comedy'}]",11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'name': 'Sandollar Productions', 'id': 5842}...",Father of the Bride Part II,11862
...,...,...,...,...,...,...,...
45456,"[{'id': 878, 'name': 'Science Fiction'}]",222848,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,"[{'name': 'Concorde-New Horizons', 'id': 4688}]",Caged Heat 3000,222848
45457,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",30840,Robin Hood,"Yet another version of the classic epic, with ...","[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...",Robin Hood,30840
45458,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",439050,رگ خواب,Rising and falling between a man and woman.,[],Subdue,439050
45459,"[{'id': 18, 'name': 'Drama'}]",111109,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,"[{'name': 'Sine Olivia', 'id': 19653}]",Century of Birthing,111109
45460,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",67758,Betrayal,"When one of her hits goes wrong, a professiona...","[{'name': 'American World Pictures', 'id': 6165}]",Betrayal,67758

In [18]:
for i, row in metadata.iterrows():
    metadata.at[i, 'credits'] = hash_table[row['id']]

In [19]:
metadata

,genres,id,original_title,overview,production_companies,title,credits
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'name': 'Pixar Animation Studios', 'id': 3}]",Toy Story,"[[{'cast_id': 14, 'character': 'Woody (voice)'..."
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",Jumanji,"[[{'cast_id': 1, 'character': 'Alan Parrish', ..."
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",Grumpier Old Men,"[[{'cast_id': 2, 'character': 'Max Goldman', '..."
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",[{'name': 'Twentieth Century Fox Film Corporat...,Waiting to Exhale,"[[{'cast_id': 1, 'character': 'Savannah 'Vanna..."
4,"[{'id': 35, 'name': 'Comedy'}]",11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'name': 'Sandollar Productions', 'id': 5842}...",Father of the Bride Part II,"[[{'cast_id': 1, 'character': 'George Banks', ..."
...,...,...,...,...,...,...,...
45456,"[{'id': 878, 'name': 'Science Fiction'}]",222848,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,"[{'name': 'Concorde-New Horizons', 'id': 4688}]",Caged Heat 3000,"[[{'cast_id': 1, 'character': 'Kira (as Cassan..."
45457,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",30840,Robin Hood,"Yet another version of the classic epic, with ...","[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...",Robin Hood,"[[{'cast_id': 1, 'character': 'Sir Robert Hode..."
45458,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",439050,رگ خواب,Rising and falling between a man and woman.,[],Subdue,"[[{'cast_id': 0, 'character': '', 'credit_id':..."
45459,"[{'id': 18, 'name': 'Drama'}]",111109,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,"[{'name': 'Sine Olivia', 'id': 19653}]",Century of Birthing,"[[{'cast_id': 1002, 'character': 'Sister Angel..."
45460,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",67758,Betrayal,"When one of her hits goes wrong, a professiona...","[{'name': 'American World Pictures', 'id': 6165}]",Betrayal,"[[{'cast_id': 6, 'character': 'Emily Shaw', 'c..."

In [20]:
def get_genres_list(row):
    genres_list = []
    for genre_dict in row:
        genres_list.append(genre_dict['name'])
    return genres_list

In [21]:
metadata['genres'] = metadata['genres'].apply(get_genres_list)

In [22]:
metadata

,genres,id,original_title,overview,production_companies,title,credits
0,"[Animation, Comedy, Family]",862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'name': 'Pixar Animation Studios', 'id': 3}]",Toy Story,"[[{'cast_id': 14, 'character': 'Woody (voice)'..."
1,"[Adventure, Fantasy, Family]",8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",Jumanji,"[[{'cast_id': 1, 'character': 'Alan Parrish', ..."
2,"[Romance, Comedy]",15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",Grumpier Old Men,"[[{'cast_id': 2, 'character': 'Max Goldman', '..."
3,"[Comedy, Drama, Romance]",31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",[{'name': 'Twentieth Century Fox Film Corporat...,Waiting to Exhale,"[[{'cast_id': 1, 'character': 'Savannah 'Vanna..."
4,[Comedy],11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'name': 'Sandollar Productions', 'id': 5842}...",Father of the Bride Part II,"[[{'cast_id': 1, 'character': 'George Banks', ..."
...,...,...,...,...,...,...,...
45456,[Science Fiction],222848,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,"[{'name': 'Concorde-New Horizons', 'id': 4688}]",Caged Heat 3000,"[[{'cast_id': 1, 'character': 'Kira (as Cassan..."
45457,"[Drama, Action, Romance]",30840,Robin Hood,"Yet another version of the classic epic, with ...","[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...",Robin Hood,"[[{'cast_id': 1, 'character': 'Sir Robert Hode..."
45458,"[Drama, Family]",439050,رگ خواب,Rising and falling between a man and woman.,[],Subdue,"[[{'cast_id': 0, 'character': '', 'credit_id':..."
45459,[Drama],111109,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,"[{'name': 'Sine Olivia', 'id': 19653}]",Century of Birthing,"[[{'cast_id': 1002, 'character': 'Sister Angel..."
45460,"[Action, Drama, Thriller]",67758,Betrayal,"When one of her hits goes wrong, a professiona...","[{'name': 'American World Pictures', 'id': 6165}]",Betrayal,"[[{'cast_id': 6, 'character': 'Emily Shaw', 'c..."

In [23]:
def get_production_companies(row):
    production_list = []
    for production_dict in row:
        production_list.append(production_dict['name'])
    return production_list

In [24]:
metadata['production_companies'][0]

[{'name': 'Pixar Animation Studios', 'id': 3}]

In [25]:
metadata['production_companies'] = metadata['production_companies'].apply(get_production_companies)

In [26]:
metadata

,genres,id,original_title,overview,production_companies,title,credits
0,"[Animation, Comedy, Family]",862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",[Pixar Animation Studios],Toy Story,"[[{'cast_id': 14, 'character': 'Woody (voice)'..."
1,"[Adventure, Fantasy, Family]",8844,Jumanji,When siblings Judy and Peter discover an encha...,"[TriStar Pictures, Teitler Film, Interscope Co...",Jumanji,"[[{'cast_id': 1, 'character': 'Alan Parrish', ..."
2,"[Romance, Comedy]",15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[Warner Bros., Lancaster Gate]",Grumpier Old Men,"[[{'cast_id': 2, 'character': 'Max Goldman', '..."
3,"[Comedy, Drama, Romance]",31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",[Twentieth Century Fox Film Corporation],Waiting to Exhale,"[[{'cast_id': 1, 'character': 'Savannah 'Vanna..."
4,[Comedy],11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[Sandollar Productions, Touchstone Pictures]",Father of the Bride Part II,"[[{'cast_id': 1, 'character': 'George Banks', ..."
...,...,...,...,...,...,...,...
45456,[Science Fiction],222848,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,[Concorde-New Horizons],Caged Heat 3000,"[[{'cast_id': 1, 'character': 'Kira (as Cassan..."
45457,"[Drama, Action, Romance]",30840,Robin Hood,"Yet another version of the classic epic, with ...","[Westdeutscher Rundfunk (WDR), Working Title F...",Robin Hood,"[[{'cast_id': 1, 'character': 'Sir Robert Hode..."
45458,"[Drama, Family]",439050,رگ خواب,Rising and falling between a man and woman.,[],Subdue,"[[{'cast_id': 0, 'character': '', 'credit_id':..."
45459,[Drama],111109,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,[Sine Olivia],Century of Birthing,"[[{'cast_id': 1002, 'character': 'Sister Angel..."
45460,"[Action, Drama, Thriller]",67758,Betrayal,"When one of her hits goes wrong, a professiona...",[American World Pictures],Betrayal,"[[{'cast_id': 6, 'character': 'Emily Shaw', 'c..."

In [27]:
def is_not_null_list(row):
    return row != []

In [28]:
metadata = metadata[metadata['production_companies'].apply(is_not_null_list)]

In [29]:
metadata

,genres,id,original_title,overview,production_companies,title,credits
0,"[Animation, Comedy, Family]",862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",[Pixar Animation Studios],Toy Story,"[[{'cast_id': 14, 'character': 'Woody (voice)'..."
1,"[Adventure, Fantasy, Family]",8844,Jumanji,When siblings Judy and Peter discover an encha...,"[TriStar Pictures, Teitler Film, Interscope Co...",Jumanji,"[[{'cast_id': 1, 'character': 'Alan Parrish', ..."
2,"[Romance, Comedy]",15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[Warner Bros., Lancaster Gate]",Grumpier Old Men,"[[{'cast_id': 2, 'character': 'Max Goldman', '..."
3,"[Comedy, Drama, Romance]",31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",[Twentieth Century Fox Film Corporation],Waiting to Exhale,"[[{'cast_id': 1, 'character': 'Savannah 'Vanna..."
4,[Comedy],11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[Sandollar Productions, Touchstone Pictures]",Father of the Bride Part II,"[[{'cast_id': 1, 'character': 'George Banks', ..."
...,...,...,...,...,...,...,...
45455,[Horror],289923,The Burkittsville 7,A film archivist revisits the story of Rustin ...,"[Neptune Salad Entertainment, Pirie Productions]",The Burkittsville 7,"[[{'cast_id': 2, 'character': 'Branwall', 'cre..."
45456,[Science Fiction],222848,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,[Concorde-New Horizons],Caged Heat 3000,"[[{'cast_id': 1, 'character': 'Kira (as Cassan..."
45457,"[Drama, Action, Romance]",30840,Robin Hood,"Yet another version of the classic epic, with ...","[Westdeutscher Rundfunk (WDR), Working Title F...",Robin Hood,"[[{'cast_id': 1, 'character': 'Sir Robert Hode..."
45459,[Drama],111109,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,[Sine Olivia],Century of Birthing,"[[{'cast_id': 1002, 'character': 'Sister Angel..."
45460,"[Action, Drama, Thriller]",67758,Betrayal,"When one of her hits goes wrong, a professiona...",[American World Pictures],Betrayal,"[[{'cast_id': 6, 'character': 'Emily Shaw', 'c..."

In [30]:
def tokenize_overview(row):
    return row.split(' ')

In [31]:
metadata['overview'] = metadata['overview'].apply(tokenize_overview)

/tmp/ipykernel_23629/3159996735.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata['overview'] = metadata['overview'].apply(tokenize_overview)

In [32]:
'hdsnj ijdn j'.replace(' ','')

'hdsnjijdnj'

In [33]:
def get_n_top_cast(n):
    def get_top_cast(row):
        top_cast = []
        i = 0
        for cast in row[0]:
            i += 1
            top_cast.append(cast['name'].replace(' ', ''))
            if i >= n:
                break
        return top_cast
    return get_top_cast

In [34]:
metadata['cast'] = metadata['credits'].apply(get_n_top_cast(5))

/tmp/ipykernel_23629/2001976994.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata['cast'] = metadata['credits'].apply(get_n_top_cast(5))

In [35]:
metadata

,genres,id,original_title,overview,production_companies,title,credits,cast
0,"[Animation, Comedy, Family]",862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...",[Pixar Animation Studios],Toy Story,"[[{'cast_id': 14, 'character': 'Woody (voice)'...","[TomHanks, TimAllen, DonRickles, JimVarney, Wa..."
1,"[Adventure, Fantasy, Family]",8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[TriStar Pictures, Teitler Film, Interscope Co...",Jumanji,"[[{'cast_id': 1, 'character': 'Alan Parrish', ...","[RobinWilliams, JonathanHyde, KirstenDunst, Br..."
2,"[Romance, Comedy]",15602,Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ...","[Warner Bros., Lancaster Gate]",Grumpier Old Men,"[[{'cast_id': 2, 'character': 'Max Goldman', '...","[WalterMatthau, JackLemmon, Ann-Margret, Sophi..."
3,"[Comedy, Drama, Romance]",31357,Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ...",[Twentieth Century Fox Film Corporation],Waiting to Exhale,"[[{'cast_id': 1, 'character': 'Savannah 'Vanna...","[WhitneyHouston, AngelaBassett, LorettaDevine,..."
4,[Comedy],11862,Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr...","[Sandollar Productions, Touchstone Pictures]",Father of the Bride Part II,"[[{'cast_id': 1, 'character': 'George Banks', ...","[SteveMartin, DianeKeaton, MartinShort, Kimber..."
...,...,...,...,...,...,...,...,...
45455,[Horror],289923,The Burkittsville 7,"[A, film, archivist, revisits, the, story, of,...","[Neptune Salad Entertainment, Pirie Productions]",The Burkittsville 7,"[[{'cast_id': 2, 'character': 'Branwall', 'cre...","[MontyBane, LucyButler, DavidGrammer, BillDreg..."
45456,[Science Fiction],222848,Caged Heat 3000,"[It's, the, year, 3000, AD., The, world's, mos...",[Concorde-New Horizons],Caged Heat 3000,"[[{'cast_id': 1, 'character': 'Kira (as Cassan...","[LisaBoyle, KenaLand, ZanetaPolard, DonYanan, ..."
45457,"[Drama, Action, Romance]",30840,Robin Hood,"[Yet, another, version, of, the, classic, epic...","[Westdeutscher Rundfunk (WDR), Working Title F...",Robin Hood,"[[{'cast_id': 1, 'character': 'Sir Robert Hode...","[PatrickBergin, UmaThurman, DavidMorrissey, Jü..."
45459,[Drama],111109,Siglo ng Pagluluwal,"[An, artist, struggles, to, finish, his, work,...",[Sine Olivia],Century of Birthing,"[[{'cast_id': 1002, 'character': 'Sister Angel...","[AngelAquino, PerryDizon, HazelOrencio, JoelTo..."
45460,"[Action, Drama, Thriller]",67758,Betrayal,"[When, one, of, her, hits, goes, wrong,, a, pr...",[American World Pictures],Betrayal,"[[{'cast_id': 6, 'character': 'Emily Shaw', 'c...","[ErikaEleniak, AdamBaldwin, JulieduPage, James..."

In [36]:
metadata['credits'][0][1]

[{'credit_id': '52fe4284c3a36847f8024f49',
  'department': 'Directing',
  'gender': 2,
  'id': 7879,
  'job': 'Director',
  'name': 'John Lasseter',
  'profile_path': '/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg'},
 {'credit_id': '52fe4284c3a36847f8024f4f',
  'department': 'Writing',
  'gender': 2,
  'id': 12891,
  'job': 'Screenplay',
  'name': 'Joss Whedon',
  'profile_path': '/dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg'},
 {'credit_id': '52fe4284c3a36847f8024f55',
  'department': 'Writing',
  'gender': 2,
  'id': 7,
  'job': 'Screenplay',
  'name': 'Andrew Stanton',
  'profile_path': '/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg'},
 {'credit_id': '52fe4284c3a36847f8024f5b',
  'department': 'Writing',
  'gender': 2,
  'id': 12892,
  'job': 'Screenplay',
  'name': 'Joel Cohen',
  'profile_path': '/dAubAiZcvKFbboWlj7oXOkZnTSu.jpg'},
 {'credit_id': '52fe4284c3a36847f8024f61',
  'department': 'Writing',
  'gender': 0,
  'id': 12893,
  'job': 'Screenplay',
  'name': 'Alec Sokolow',
  'profile_path': '/v79vlRYi94BZUQnkkyznbGUZLjT.jpg'},
 {'credit_id': '52fe4284c3a36847f8024f67',
  'department': 'Production',
  'gender': 1,
  'id': 12894,
  'job': 'Producer',
  'name': 'Bonnie Arnold',
  'profile_path': None},
 {'credit_id': '52fe4284c3a36847f8024f6d',
  'department': 'Production',
  'gender': 0,
  'id': 12895,
  'job': 'Executive Producer',
  'name': 'Ed Catmull',
  'profile_path': None},
 {'credit_id': '52fe4284c3a36847f8024f73',
  'department': 'Production',
  'gender': 2,
  'id': 12896,
  'job': 'Producer',
  'name': 'Ralph Guggenheim',
  'profile_path': None},
 {'credit_id': '52fe4284c3a36847f8024f79',
  'department': 'Production',
  'gender': 2,
  'id': 12897,
  'job': 'Executive Producer',
  'name': 'Steve Jobs',
  'profile_path': '/mOMP3SwD5qWQSR0ldCIByd3guTV.jpg'},
 {'credit_id': '52fe4284c3a36847f8024f8b',
  'department': 'Editing',
  'gender': 2,
  'id': 8,
  'job': 'Editor',
  'name': 'Lee Unkrich',
  'profile_path': '/bdTCCXjgOV3YyaNmLGYGOxFQMOc.jpg'},
 {'credit_id': '52fe4284c3a36847f8024f91',
  'department': 'Art',
  'gender': 2,
  'id': 7883,
  'job': 'Art Direction',
  'name': 'Ralph Eggleston',
  'profile_path': '/uUfcGKDsKO1aROMpXRs67Hn6RvR.jpg'},
 {'credit_id': '598331bf925141421201044b',
  'department': 'Editing',
  'gender': 2,
  'id': 1168870,
  'job': 'Editor',
  'name': 'Robert Gordon',
  'profile_path': None},
 {'credit_id': '5892168cc3a36809660095f9',
  'department': 'Sound',
  'gender': 0,
  'id': 1552883,
  'job': 'Foley Editor',
  'name': 'Mary Helen Leasman',
  'profile_path': None},
 {'credit_id': '5531824d9251415289000945',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1453514,
  'job': 'Animation',
  'name': 'Kim Blanchette',
  'profile_path': None},
 {'credit_id': '589215969251412dcb009bf6',
  'department': 'Sound',
  'gender': 0,
  'id': 1414182,
  'job': 'ADR Editor',
  'name': 'Marilyn McCoppen',
  'profile_path': None},
 {'credit_id': '589217099251412dc500a018',
  'department': 'Sound',
  'gender': 2,
  'id': 7885,
  'job': 'Orchestrator',
  'name': 'Randy Newman',
  'profile_path': '/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg'},
 {'credit_id': '5693e6b29251417b0e0000e3',
  'department': 'Editing',
  'gender': 0,
  'id': 1429549,
  'job': 'Color Timer',
  'name': 'Dale E. Grahn',
  'profile_path': None},
 {'credit_id': '572e2522c3a36869e6001a9c',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 7949,
  'job': 'CG Painter',
  'name': 'Robin Cooper',
  'profile_path': None},
 {'credit_id': '574f12309251415ca1000012',
  'department': 'Writing',
  'gender': 2,
  'id': 7879,
  'job': 'Original Story',
  'name': 'John Lasseter',
  'profile_path': '/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg'},
 {'credit_id': '574f1240c3a3682e7300001c',
  'department': 'Writing',
  'gender': 2,
  'id': 12890,
  'job': 'Original Story',
  'name': 'Pete Docter',
  'profile_path': '/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg'},
 {'credit_id': '574f12519251415c92000015',
  'department': 'Writing',
  'gender': 0,
  'id': 7911,
  'job': 'Original Story',
  'name': 'Joe Ranft',
  'profile_path': '/f1BoWC2JbCcfP1e5hKfGsxkHzVU.jpg'},
 {'credit_id': '574f12cec3a3682e82000022',
  'department': 'Crew',
  'gender': 0,
  'id': 1629419,
  'job': 'Post Production Supervisor',
  'name': 'Patsy Bouge',
  'profile_path': None},
 {'credit_id': '574f14f19251415ca1000082',
  'department': 'Art',
  'gender': 0,
  'id': 7961,
  'job': 'Sculptor',
  'name': 'Norm DeCarlo',
  'profile_path': None},
 {'credit_id': '5751ae4bc3a3683772002b7f',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 12905,
  'job': 'Animation Director',
  'name': 'Ash Brannon',
  'profile_path': '/6ueWgPEEBHvS3De2BHYQnYjRTig.jpg'},
 {'credit_id': '5891edbe9251412dc5007cd6',
  'department': 'Sound',
  'gender': 2,
  'id': 7885,
  'job': 'Music',
  'name': 'Randy Newman',
  'profile_path': '/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg'},
 {'credit_id': '589213d39251412dc8009832',
  'department': 'Directing',
  'gender': 0,
  'id': 1748707,
  'job': 'Layout',
  'name': 'Roman Figun',
  'profile_path': None},
 {'credit_id': '5892173dc3a3680968009351',
  'department': 'Sound',
  'gender': 2,
  'id': 4949,
  'job': 'Orchestrator',
  'name': 'Don Davis',
  'profile_path': None},
 {'credit_id': '589217cec3a3686b0a0052ba',
  'department': 'Sound',
  'gender': 0,
  'id': 1372885,
  'job': 'Music Editor',
  'name': 'James Flamberg',
  'profile_path': None},
 {'credit_id': '58921831c3a3686348004a64',
  'department': 'Editing',
  'gender': 0,
  'id': 1739962,
  'job': 'Negative Cutter',
  'name': 'Mary Beth Smith',
  'profile_path': None},
 {'credit_id': '58921838c3a36809700096c0',
  'department': 'Editing',
  'gender': 0,
  'id': 1748513,
  'job': 'Negative Cutter',
  'name': 'Rick Mackay',
  'profile_path': None},
 {'credit_id': '589218429251412dd1009d1b',
  'department': 'Art',
  'gender': 0,
  'id': 1458006,
  'job': 'Title Designer',
  'name': 'Susan Bradley',
  'profile_path': None},
 {'credit_id': '5891ed99c3a3680966007670',
  'department': 'Crew',
  'gender': 0,
  'id': 1748557,
  'job': 'Supervising Technical Director',
  'name': 'William Reeves',
  'profile_path': None},
 {'credit_id': '5891edcec3a3686b0a002eb2',
  'department': 'Sound',
  'gender': 2,
  'id': 7885,
  'job': 'Songs',
  'name': 'Randy Newman',
  'profile_path': '/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg'},
 {'credit_id': '5891edf9c3a36809700075e6',
  'department': 'Writing',
  'gender': 2,
  'id': 7,
  'job': 'Original Story',
  'name': 'Andrew Stanton',
  'profile_path': '/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg'},
 {'credit_id': '58920f0b9251412dd7009104',
  'department': 'Crew',
  'gender': 2,
  'id': 12890,
  'job': 'Supervising Animator',
  'name': 'Pete Docter',
  'profile_path': '/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg'},
 {'credit_id': '58920f1fc3a3680977009021',
  'department': 'Sound',
  'gender': 2,
  'id': 2216,
  'job': 'Sound Designer',
  'name': 'Gary Rydstrom',
  'profile_path': '/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg'},
 {'credit_id': '58920f389251412dd700912d',
  'department': 'Production',
  'gender': 0,
  'id': 12909,
  'job': 'Production Supervisor',
  'name': 'Karen Robert Jackson',
  'profile_path': None},
 {'credit_id': '58920fbd9251412dcb00969c',
  'department': 'Crew',
  'gender': 0,
  'id': 953331,
  'job': 'Executive Music Producer',
  'name': 'Chris Montan',
  'profile_path': None},
 {'credit_id': '589210069251412dd7009219',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 7893,
  'job': 'Animation Director',
  'name': 'Rich Quade',
  'profile_path': None},
 {'credit_id': '589210329251412dcd00943b',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 8025,
  'job': 'Animation',
  'name': 'Michael Berenstein',
  'profile_path': None},
 {'credit_id': '5892103bc3a368096a009180',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 78009,
  'job': 'Animation',
  'name': 'Colin Brady',
  'profile_path': None},
 {'credit_id': '5892105dc3a3680968008db2',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1748682,
  'job': 'Animation',
  'name': 'Davey Crockett Feiten',
  'profile_path': None},
 {'credit_id': '589210669251412dcd009466',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1454030,
  'job': 'Animation',
  'name': 'Angie Glocka',
  'profile_path': None},
 {'credit_id': '5892107c9251412dd1009613',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1748683,
  'job': 'Animation',
  'name': 'Rex Grignon',
  'profile_path': None},
 {'credit_id': '5892108ac3a3680973008d3f',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1748684,
  'job': 'Animation',
  'name': 'Tom K. Gurney',
  'profile_path': None},
 {'credit_id': '58921093c3a3686348004477',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 8029,
  'job': 'Animation',
  'name': 'Jimmy Hayward',
  'profile_path': '/lTDRpudEY7BDwTefXbXzMlmb0ui.jpg'},
 {'credit_id': '5892109b9251412dcd0094b0',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1426773,
  'job': 'Animation',
  'name': 'Hal T. Hickel',
  'profile_path': None},
 {'credit_id': '589210a29251412dc5009a29',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 8035,
  'job': 'Animation',
  'name': 'Karen Kiser',
  'profile_path': None},
 {'credit_id': '589210ccc3a3680977009191',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1748688,
  'job': 'Animation',
  'name': 'Anthony B. LaMolinara',
  'profile_path': None},
 {'credit_id': '589210d7c3a3686b0a004c1f',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 587314,
  'job': 'Animation',
  'name': 'Guionne Leroy',
  'profile_path': None},
 {'credit_id': '589210e1c3a36809770091a7',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 7918,
  'job': 'Animation',
  'name': 'Bud Luckey',
  'profile_path': '/pcCh7G19FKMNijmPQg1PMH1btic.jpg'},
 {'credit_id': '589210ee9251412dc200978a',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1748689,
  'job': 'Animation',
  'name': 'Les Major',
  'profile_path': None},
 {'credit_id': '589210fa9251412dc8009595',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 7892,
  'job': 'Animation',
  'name': 'Glenn McQueen',
  'profile_path': None},
 {'credit_id': '589211029251412dc8009598',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 555795,
  'job': 'Animation',
  'name': 'Mark Oftedal',
  'profile_path': None},
 {'credit_id': '5892110b9251412dc800959d',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 7882,
  'job': 'Animation',
  'name': 'Jeff Pidgeon',
  'profile_path': '/yLddkg5HcgbJg00cS13GVBnP0HY.jpg'},
 {'credit_id': '58921113c3a36863480044e4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 8017,
  'job': 'Animation',
  'name': 'Jeff Pratt',
  'profile_path': None},
 {'credit_id': '5892111c9251412dcb0097e9',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1184140,
  'job': 'Animation',
  'name': 'Steve Rabatich',
  'profile_path': None},
 {'credit_id': '58921123c3a36809700090f6',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 8049,
  'job': 'Animation',
  'name': 'Roger Rose',
  'profile_path': None},
 {'credit_id': '5892112b9251412dcb0097fb',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1509559,
  'job': 'Animation',
  'name': 'Steve Segal',
  'profile_path': None},
 {'credit_id': '589211349251412dc80095c3',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1748691,
  'job': 'Animation',
  'name': 'Doug Sheppeck',
  'profile_path': None},
 {'credit_id': '5892113cc3a3680970009106',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 8050,
  'job': 'Animation',
  'name': 'Alan Sperling',
  'profile_path': None},
 {'credit_id': '58921148c3a3686b0a004c99',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 8010,
  'job': 'Animation',
  'name': 'Doug Sweetland',
  'profile_path': None},
 {'credit_id': '58921150c3a3680966009125',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 8044,
  'job': 'Animation',
  'name': 'David Tart',
  'profile_path': None},
 {'credit_id': '589211629251412dc5009b00',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1454034,
  'job': 'Animation',
  'name': 'Ken Willard',
  'profile_path': None},
 {'credit_id': '589211c1c3a3686b0a004d28',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 7887,
  'job': 'Visual Effects Supervisor',
  'name': 'Thomas Porter',
  'profile_path': None},
 {'credit_id': '589211d4c3a3680968008ed9',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1406878,
  'job': 'Visual Effects',
  'name': 'Mark Thomas Henne',
  'profile_path': None},
 {'credit_id': '589211f59251412dd4008e65',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1748698,
  'job': 'Visual Effects',
  'name': 'Oren Jacob',
  'profile_path': None},
 {'credit_id': '58921242c3a368096a00939b',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1748699,
  'job': 'Visual Effects',
  'name': 'Darwyn Peachey',
  'profile_path': None},
 {'credit_id': '5892124b9251412dc5009bd2',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1748701,
  'job': 'Visual Effects',
  'name': 'Mitch Prater',
  'profile_path': None},
 {'credit_id': '58921264c3a3686b0a004dbf',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1748703,
  'job': 'Visual Effects',
  'name': 'Brian M. Rosen',
  'profile_path': None},
 {'credit_id': '589212709251412dcd009676',
  'department': 'Lighting',
  'gender': 1,
  'id': 12912,
  'job': 'Lighting Supervisor',
  'name': 'Sharon Calahan',
  'profile_path': None},
 {'credit_id': '5892127fc3a3686b0a004de5',
  'department': 'Lighting',
  'gender': 0,
  'id': 7899,
  'job': 'Lighting Supervisor',
  'name': 'Galyn Susman',
  'profile_path': None},
 {'credit_id': '589212cdc3a3680970009268',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 12915,
  'job': 'CG Painter',
  'name': 'William Cone',
  'profile_path': None},
 {'credit_id': '5892130f9251412dc8009791',
  'department': 'Art',
  'gender': 0,
  'id': 1748705,
  'job': 'Sculptor',
  'name': 'Shelley Daniels Lekven',
  'profile_path': None},
 {'credit_id': '5892131c9251412dd4008f4c',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 7889,
  'job': 'Character Designer',
  'name': 'Bob Pauley',
  'profile_path': None},
 {'credit_id': '589213249251412dd100987b',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 7918,
  'job': 'Character Designer',
  'name': 'Bud Luckey',
  'profile_path': '/pcCh7G19FKMNijmPQg1PMH1btic.jpg'},
 {'credit_id': '5892132b9251412dc80097b1',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 7,
  'job': 'Character Designer',
  'name': 'Andrew Stanton',
  'profile_path': '/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg'},
 {'credit_id': '58921332c3a368634800467b',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 12915,
  'job': 'Character Designer',
  'name': 'William Cone',
  'profile_path': None},
 {'credit_id': '5892135f9251412dd4008f90',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1748706,
  'job': 'Character Designer',
  'name': 'Steve Johnson',
  'profile_path': None},
 {'credit_id': '58921384c3a3680973008fd4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1176752,
  'job': 'Character Designer',
  'name': 'Dan Haskett',
  'profile_path': None},
 {'credit_id': '5892138e9251412dc20099fc',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1088034,
  'job': 'Character Designer',
  'name': 'Tom Holloway',
  'profile_path': '/a0r0T2usTBpgMI5aZbRBDW1fTl8.jpg'},
 {'credit_id': '58921395c3a368097700942f',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1447465,
  'job': 'Character Designer',
  'name': 'Jean Gillmore',
  'profile_path': None},
 {'credit_id': '589213e2c3a3680973009026',
  'department': 'Directing',
  'gender': 0,
  'id': 1748709,
  'job': 'Layout',
  'name': 'Desirée Mourad',
  'profile_path': None},
 {'credit_id': '589214099251412dc5009d57',
  'department': 'Art',
  'gender': 0,
  'id': 1748710,
  'job': 'Set Dresser',
  'name': "Kelly O'Connell",
  'profile_path': None},
 {'credit_id': '58921411c3a3686b0a004f70',
  'department': 'Art',
  'gender': 0,
  'id': 1443471,
  'job': 'Set Dresser',
  'name': 'Sonoko Konishi',
  'profile_path': None},
 {'credit_id': '58921434c3a368096a00956e',
  'department': 'Art',
  'gender': 0,
  'id': 1748711,
  'job': 'Set Dresser',
  'name': 'Ann M. Rockwell',
  'profile_path': None},
 {'credit_id': '5892144ac3a36809680090de',
  'department': 'Editing',
  'gender': 0,
  'id': 1748712,
  'job': 'Editorial Manager',
  'name': 'Julie M. McDonald',
  'profile_path': None},
 {'credit_id': '58921479c3a368096800910f',
  'department': 'Editing',
  'gender': 0,
  'id': 1589729,
  'job': 'Assistant Editor',
  'name': 'Robin Lee',
  'profile_path': None},
 {'credit_id': '5892148b9251412dd10099cc',
  'department': 'Editing',
  'gender': 0,
  'id': 1748716,
  'job': 'Assistant Editor',
  'name': 'Tom Freeman',
  'profile_path': None},
 {'credit_id': '589214959251412dcb009b1f',
  'department': 'Editing',
  'gender': 0,
  'id': 1748717,
  'job': 'Assistant Editor',
  'name': 'Ada Cochavi',
  'profile_path': None},
 {'credit_id': '5892149ec3a3686348004798',
  'department': 'Editing',
  'gender': 0,
  'id': 1336438,
  'job': 'Assistant Editor',
  'name': 'Dana Mulligan',
  'profile_path': None},
 {'credit_id': '589214adc3a368096a0095db',
  'department': 'Editing',
  'gender': 0,
  'id': 1748718,
  'job': 'Editorial Coordinator',
  'name': 'Deirdre Morrison',
  'profile_path': None},
 {'credit_id': '589214c7c3a368097700952b',
  'department': 'Production',
  'gender': 0,
  'id': 1748719,
  'job': 'Production Coordinator',
  'name': 'Lori Lombardo',
  'profile_path': None},
 {'credit_id': '589214cec3a368096a009603',
  'department': 'Production',
  'gender': 0,
  'id': 1748720,
  'job': 'Production Coordinator',
  'name': 'Ellen Devine',
  'profile_path': None},
 {'credit_id': '589214e39251412dc8009904',
  'department': 'Crew',
  'gender': 0,
  'id': 1468014,
  'job': 'Unit Publicist',
  'name': 'Lauren Beth Strogoff',
  'profile_path': None},
 {'credit_id': '58921544c3a3686b0a00507d',
  'department': 'Sound',
  'gender': 2,
  'id': 2216,
  'job': 'Sound Re-Recording Mixer',
  'name': 'Gary Rydstrom',
  'profile_path': '/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg'},
 {'credit_id': '5892154c9251412dd1009a56',
  'department': 'Sound',
  'gender': 0,
  'id': 1425978,
  'job': 'Sound Re-Recording Mixer',
  'name': 'Gary Summers',
  'profile_path': None},
 {'credit_id': '58921555c3a36809680091bd',
  'department': 'Sound',
  'gender': 2,
  'id': 8276,
  'job': 'Supervising Sound Editor',
  'name': 'Tim Holland',
  'profile_path': None},
 {'credit_id': '589215c39251412dcb009c12',
  'department': 'Sound',
  'gender': 0,
  'id': 7069,
  'job': 'Sound Effects Editor',
  'name': 'Pat Jackson',
  'profile_path': None},
 {'credit_id': '58921698c3a368096a009788',
  'department': 'Crew',
  'gender': 2,
  'id': 15894,
  'job': 'Sound Design Assistant',
  'name': 'Tom Myers',
  'profile_path': None},
 {'credit_id': '589216a89251412dc2009ca4',
  'department': 'Sound',
  'gender': 0,
  'id': 1414177,
  'job': 'Assistant Sound Editor',
  'name': 'J.R. Grubbs',
  'profile_path': None},
 {'credit_id': '589216c19251412dc2009cb9',
  'department': 'Sound',
  'gender': 1,
  'id': 1748724,
  'job': 'Assistant Sound Editor',
  'name': 'Susan Sanford',
  'profile_path': None},
 {'credit_id': '589216ccc3a3680973009274',
  'department': 'Sound',
  'gender': 0,
  'id': 1748725,
  'job': 'Assistant Sound Editor',
  'name': 'Susan Popovic',
  'profile_path': None},
 {'credit_id': '589216d79251412dc8009aa0',
  'department': 'Sound',
  'gender': 0,
  'id': 8067,
  'job': 'Assistant Sound Editor',
  'name': 'Dan Engstrom',
  'profile_path': None},
 {'credit_id': '589216e49251412dcd009a4f',
  'department': 'Production',
  'gender': 1,
  'id': 7902,
  'job': 'Casting Consultant',
  'name': 'Ruth Lambert',
  'profile_path': None},
 {'credit_id': '589216f39251412dc2009cf3',
  'department': 'Production',
  'gender': 0,
  'id': 84493,
  'job': 'ADR Voice Casting',
  'name': 'Mickie McGowan',

In [37]:
def get_director(row):
    directors = []
    for job in row[1]:
        if job['job'] == 'Director':
            directors.append(job['name'].replace(' ', ''))
    return directors

In [38]:
metadata['directors'] = metadata['credits'].apply(get_director)

/tmp/ipykernel_23629/1101475659.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata['directors'] = metadata['credits'].apply(get_director)

In [39]:
metadata

,genres,id,original_title,overview,production_companies,title,credits,cast,directors
0,"[Animation, Comedy, Family]",862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...",[Pixar Animation Studios],Toy Story,"[[{'cast_id': 14, 'character': 'Woody (voice)'...","[TomHanks, TimAllen, DonRickles, JimVarney, Wa...",[JohnLasseter]
1,"[Adventure, Fantasy, Family]",8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[TriStar Pictures, Teitler Film, Interscope Co...",Jumanji,"[[{'cast_id': 1, 'character': 'Alan Parrish', ...","[RobinWilliams, JonathanHyde, KirstenDunst, Br...",[JoeJohnston]
2,"[Romance, Comedy]",15602,Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ...","[Warner Bros., Lancaster Gate]",Grumpier Old Men,"[[{'cast_id': 2, 'character': 'Max Goldman', '...","[WalterMatthau, JackLemmon, Ann-Margret, Sophi...",[HowardDeutch]
3,"[Comedy, Drama, Romance]",31357,Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ...",[Twentieth Century Fox Film Corporation],Waiting to Exhale,"[[{'cast_id': 1, 'character': 'Savannah 'Vanna...","[WhitneyHouston, AngelaBassett, LorettaDevine,...",[ForestWhitaker]
4,[Comedy],11862,Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr...","[Sandollar Productions, Touchstone Pictures]",Father of the Bride Part II,"[[{'cast_id': 1, 'character': 'George Banks', ...","[SteveMartin, DianeKeaton, MartinShort, Kimber...",[CharlesShyer]
...,...,...,...,...,...,...,...,...,...
45455,[Horror],289923,The Burkittsville 7,"[A, film, archivist, revisits, the, story, of,...","[Neptune Salad Entertainment, Pirie Productions]",The Burkittsville 7,"[[{'cast_id': 2, 'character': 'Branwall', 'cre...","[MontyBane, LucyButler, DavidGrammer, BillDreg...",[BenRock]
45456,[Science Fiction],222848,Caged Heat 3000,"[It's, the, year, 3000, AD., The, world's, mos...",[Concorde-New Horizons],Caged Heat 3000,"[[{'cast_id': 1, 'character': 'Kira (as Cassan...","[LisaBoyle, KenaLand, ZanetaPolard, DonYanan, ...",[AaronOsborne]
45457,"[Drama, Action, Romance]",30840,Robin Hood,"[Yet, another, version, of, the, classic, epic...","[Westdeutscher Rundfunk (WDR), Working Title F...",Robin Hood,"[[{'cast_id': 1, 'character': 'Sir Robert Hode...","[PatrickBergin, UmaThurman, DavidMorrissey, Jü...",[JohnIrvin]
45459,[Drama],111109,Siglo ng Pagluluwal,"[An, artist, struggles, to, finish, his, work,...",[Sine Olivia],Century of Birthing,"[[{'cast_id': 1002, 'character': 'Sister Angel...","[AngelAquino, PerryDizon, HazelOrencio, JoelTo...",[LavDiaz]
45460,"[Action, Drama, Thriller]",67758,Betrayal,"[When, one, of, her, hits, goes, wrong,, a, pr...",[American World Pictures],Betrayal,"[[{'cast_id': 6, 'character': 'Emily Shaw', 'c...","[ErikaEleniak, AdamBaldwin, JulieduPage, James...",[MarkL.Lester]

In [40]:
metadata['tags'] = metadata['genres'] + metadata['overview'] + metadata['cast'] + metadata['directors'] + metadata['production_companies']

/tmp/ipykernel_23629/2421798349.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata['tags'] = metadata['genres'] + metadata['overview'] + metadata['cast'] + metadata['directors'] + metadata['production_companies']

In [41]:
metadata

,genres,id,original_title,overview,production_companies,title,credits,cast,directors,tags
0,"[Animation, Comedy, Family]",862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...",[Pixar Animation Studios],Toy Story,"[[{'cast_id': 14, 'character': 'Woody (voice)'...","[TomHanks, TimAllen, DonRickles, JimVarney, Wa...",[JohnLasseter],"[Animation, Comedy, Family, Led, by, Woody,, A..."
1,"[Adventure, Fantasy, Family]",8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[TriStar Pictures, Teitler Film, Interscope Co...",Jumanji,"[[{'cast_id': 1, 'character': 'Alan Parrish', ...","[RobinWilliams, JonathanHyde, KirstenDunst, Br...",[JoeJohnston],"[Adventure, Fantasy, Family, When, siblings, J..."
2,"[Romance, Comedy]",15602,Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ...","[Warner Bros., Lancaster Gate]",Grumpier Old Men,"[[{'cast_id': 2, 'character': 'Max Goldman', '...","[WalterMatthau, JackLemmon, Ann-Margret, Sophi...",[HowardDeutch],"[Romance, Comedy, A, family, wedding, reignite..."
3,"[Comedy, Drama, Romance]",31357,Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ...",[Twentieth Century Fox Film Corporation],Waiting to Exhale,"[[{'cast_id': 1, 'character': 'Savannah 'Vanna...","[WhitneyHouston, AngelaBassett, LorettaDevine,...",[ForestWhitaker],"[Comedy, Drama, Romance, Cheated, on,, mistrea..."
4,[Comedy],11862,Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr...","[Sandollar Productions, Touchstone Pictures]",Father of the Bride Part II,"[[{'cast_id': 1, 'character': 'George Banks', ...","[SteveMartin, DianeKeaton, MartinShort, Kimber...",[CharlesShyer],"[Comedy, Just, when, George, Banks, has, recov..."
...,...,...,...,...,...,...,...,...,...,...
45455,[Horror],289923,The Burkittsville 7,"[A, film, archivist, revisits, the, story, of,...","[Neptune Salad Entertainment, Pirie Productions]",The Burkittsville 7,"[[{'cast_id': 2, 'character': 'Branwall', 'cre...","[MontyBane, LucyButler, DavidGrammer, BillDreg...",[BenRock],"[Horror, A, film, archivist, revisits, the, st..."
45456,[Science Fiction],222848,Caged Heat 3000,"[It's, the, year, 3000, AD., The, world's, mos...",[Concorde-New Horizons],Caged Heat 3000,"[[{'cast_id': 1, 'character': 'Kira (as Cassan...","[LisaBoyle, KenaLand, ZanetaPolard, DonYanan, ...",[AaronOsborne],"[Science Fiction, It's, the, year, 3000, AD., ..."
45457,"[Drama, Action, Romance]",30840,Robin Hood,"[Yet, another, version, of, the, classic, epic...","[Westdeutscher Rundfunk (WDR), Working Title F...",Robin Hood,"[[{'cast_id': 1, 'character': 'Sir Robert Hode...","[PatrickBergin, UmaThurman, DavidMorrissey, Jü...",[JohnIrvin],"[Drama, Action, Romance, Yet, another, version..."
45459,[Drama],111109,Siglo ng Pagluluwal,"[An, artist, struggles, to, finish, his, work,...",[Sine Olivia],Century of Birthing,"[[{'cast_id': 1002, 'character': 'Sister Angel...","[AngelAquino, PerryDizon, HazelOrencio, JoelTo...",[LavDiaz],"[Drama, An, artist, struggles, to, finish, his..."
45460,"[Action, Drama, Thriller]",67758,Betrayal,"[When, one, of, her, hits, goes, wrong,, a, pr...",[American World Pictures],Betrayal,"[[{'cast_id': 6, 'character': 'Emily Shaw', 'c...","[ErikaEleniak, AdamBaldwin, JulieduPage, James...",[MarkL.Lester],"[Action, Drama, Thriller, When, one, of, her, ..."

In [42]:
final_data = metadata.drop(['genres', 'overview', 'production_companies', 'title', 'credits', 'cast', 'directors'], axis=1)

In [43]:
final_data

,id,original_title,tags
0,862,Toy Story,"[Animation, Comedy, Family, Led, by, Woody,, A..."
1,8844,Jumanji,"[Adventure, Fantasy, Family, When, siblings, J..."
2,15602,Grumpier Old Men,"[Romance, Comedy, A, family, wedding, reignite..."
3,31357,Waiting to Exhale,"[Comedy, Drama, Romance, Cheated, on,, mistrea..."
4,11862,Father of the Bride Part II,"[Comedy, Just, when, George, Banks, has, recov..."
...,...,...,...
45455,289923,The Burkittsville 7,"[Horror, A, film, archivist, revisits, the, st..."
45456,222848,Caged Heat 3000,"[Science Fiction, It's, the, year, 3000, AD., ..."
45457,30840,Robin Hood,"[Drama, Action, Romance, Yet, another, version..."
45459,111109,Siglo ng Pagluluwal,"[Drama, An, artist, struggles, to, finish, his..."
45460,67758,Betrayal,"[Action, Drama, Thriller, When, one, of, her, ..."

In [44]:
final_data['tags'] = final_data['tags'].apply(lambda x: ' '.join(x))

In [45]:
final_data.to_csv('dataset/processed_data.csv')

In [46]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [47]:
vectors = cv.fit_transform(final_data['tags']).toarray()

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
# similarities = cosine_similarity(vectors)
chunk_size = 500 
matrix_len = vectors.shape[0] # Not sparse numpy.ndarray

def similarity_cosine_by_chunk(start, end):
    if end > matrix_len:
        end = matrix_len
    return cosine_similarity(X=vectors[start:end], Y=vectors) # scikit-learn function

chunks = []

for chunk_start in range(0, matrix_len, chunk_size):
    cosine_similarity_chunk = similarity_cosine_by_chunk(chunk_start, chunk_start+chunk_size)
    chunks.append(cosine_similarity_chunk)

KeyboardInterrupt: